package com.dbtraining.tradeflow.repository;

import com.dbtraining.tradeflow.config.DatabaseConfig;
import com.dbtraining.tradeflow.model.Trade;
import com.dbtraining.tradeflow.model.TradeStatus;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

class TradeDAOTest {

    private static DataSource dataSource;
    private TradeDAO tradeDAO;

    @BeforeAll
    static void initSchema() throws Exception {
        dataSource = DatabaseConfig.dataSource();
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS trades (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    trade_ref VARCHAR(64) NOT NULL UNIQUE,
                    instrument_id BIGINT NOT NULL,
                    counterparty_id BIGINT NOT NULL,
                    quantity DECIMAL(18, 4) NOT NULL,
                    price DECIMAL(18, 4) NOT NULL,
                    trade_date DATE NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """);
        }
    }

    @BeforeEach
    void setUp() throws Exception {
        tradeDAO = new TradeDAO(dataSource);
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM trades;");
        }
    }

    @Test
    @DisplayName("TICKET-I044: DatabaseConfig returns singleton HikariDataSource")
    void testDatabaseConfigDataSource() {
        DataSource ds1 = DatabaseConfig.dataSource();
        DataSource ds2 = DatabaseConfig.dataSource();

        assertNotNull(ds1);
        assertSame(ds1, ds2, "DatabaseConfig.dataSource() must return a singleton instance");
    }

    @Test
    @DisplayName("TICKET-I045: TradeDAO insert and findByRef")
    void testInsertAndFindByRef() {
        Trade trade = Trade.builder()
                .tradeRef("TRD-DAO-001")
                .instrumentId(1L)
                .counterpartyId(2L)
                .quantity(new BigDecimal("100.00"))
                .price(new BigDecimal("50.25"))
                .tradeDate(LocalDate.of(2026, 3, 15))
                .status(TradeStatus.PENDING)
                .build();

        long id = tradeDAO.insert(trade);
        assertTrue(id > 0, "Insert should return generated primary key > 0");

        Optional<Trade> found = tradeDAO.findByRef("TRD-DAO-001");
        assertTrue(found.isPresent(), "Trade should be found by tradeRef");
        assertEquals("TRD-DAO-001", found.get().getTradeRef());
        assertEquals(1L, found.get().getInstrumentId());
        assertEquals(2L, found.get().getCounterpartyId());
        assertEquals(0, new BigDecimal("100.00").compareTo(found.get().getQuantity()));
        assertEquals(0, new BigDecimal("50.25").compareTo(found.get().getPrice()));
        assertEquals(TradeStatus.PENDING, found.get().getStatus());
    }

    @Test
    @DisplayName("TICKET-I045: TradeDAO findAll")
    void testFindAll() {
        Trade trade1 = Trade.builder()
                .tradeRef("TRD-DAO-002")
                .instrumentId(1L)
                .counterpartyId(2L)
                .quantity(new BigDecimal("50"))
                .price(new BigDecimal("10"))
                .tradeDate(LocalDate.of(2026, 3, 10))
                .status(TradeStatus.MATCHED)
                .build();

        Trade trade2 = Trade.builder()
                .tradeRef("TRD-DAO-003")
                .instrumentId(2L)
                .counterpartyId(3L)
                .quantity(new BigDecimal("200"))
                .price(new BigDecimal("20"))
                .tradeDate(LocalDate.of(2026, 3, 12))
                .status(TradeStatus.PENDING)
                .build();

        tradeDAO.insert(trade1);
        tradeDAO.insert(trade2);

        List<Trade> trades = tradeDAO.findAll();
        assertEquals(2, trades.size());
    }

    @Test
    @DisplayName("TICKET-I045: TradeDAO updateStatus")
    void testUpdateStatus() {
        Trade trade = Trade.builder()
                .tradeRef("TRD-DAO-004")
                .instrumentId(1L)
                .counterpartyId(1L)
                .quantity(new BigDecimal("10"))
                .price(new BigDecimal("100"))
                .tradeDate(LocalDate.now())
                .status(TradeStatus.PENDING)
                .build();

        tradeDAO.insert(trade);

        int updated = tradeDAO.updateStatus("TRD-DAO-004", TradeStatus.MATCHED);
        assertEquals(1, updated, "One row should be updated");

        Optional<Trade> found = tradeDAO.findByRef("TRD-DAO-004");
        assertTrue(found.isPresent());
        assertEquals(TradeStatus.MATCHED, found.get().getStatus());
    }
}
